const products = [
 {id:1,name:'حقيبة نوبة المنسوجة',brand:'Nuba Studio',category:'أزياء',price:820,color:'#d2c0a9',emoji:'👜',express:true},
 {id:2,name:'طقم عناية يومي',brand:'Nile Rituals',category:'عناية',price:390,color:'#d9b37e',emoji:'🧴',express:true},
 {id:3,name:'شمعة رمل الواحة',brand:'Mazar',category:'ديكور',price:260,color:'#b99472',emoji:'🕯️',express:true},
 {id:4,name:'بوكس قهوة مختصة',brand:'Savour',category:'أكل',price:315,color:'#796353',emoji:'☕',express:false},
 {id:5,name:'قميص كتان أبيض',brand:'Mushkila',category:'أزياء',price:690,color:'#ddd9cf',emoji:'👔',express:true},
 {id:6,name:'طبق خزف مرسوم',brand:'Clayton',category:'ديكور',price:420,color:'#c98262',emoji:'🏺',express:true},
];
const brands=[['Nuba Studio','إكسسوارات وحكايات من النوبة','🪡','#c8a17c'],['Nile Rituals','عناية مستوحاة من النيل','☼','#90ab8c'],['Mazar','تفاصيل دافئة لبيتك','✺','#d6a06d'],['Savour','أكل معمول بحب','♡','#bd7960']];
let cart=[]; let activeCategory='الكل';
const money=n=>`${n.toLocaleString('ar-EG')} ج.م`;
function renderProducts(){const q=document.querySelector('.search').value.trim();const express=document.querySelector('#expressFilter').checked;const list=products.filter(p=>(activeCategory==='الكل'||p.category===activeCategory)&&(!express||p.express)&&(`${p.name} ${p.brand} ${p.category}`).includes(q));document.querySelector('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" style="background:${p.color}"><span>${p.emoji}</span>${p.express?'<b>⚡ خلال ساعتين</b>':''}</div><div class="product-info"><p>${p.brand}</p><h3>${p.name}</h3><div><strong>${money(p.price)}</strong><button aria-label="أضف للسلة" onclick="addToCart(${p.id})">+</button></div></div></article>`).join('')||'<p class="empty">مفيش منتجات مطابقة للبحث.</p>'}
function renderBrands(){document.querySelector('#brandGrid').innerHTML=brands.map(b=>`<article class="brand-card"><div class="brand-symbol" style="background:${b[3]}">${b[2]}</div><div><h3>${b[0]}</h3><p>${b[1]}</p><a href="#products">تسوقي الآن ←</a></div></article>`).join('')}
function addToCart(id){const product=products.find(p=>p.id===id);const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...product,qty:1});renderCart();document.querySelector('#toast').textContent=`تمت إضافة ${product.name} للسلة`;document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),2200)}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0), subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><span class="mini-image" style="background:${x.color}">${x.emoji}</span><div><h3>${x.name}</h3><p>${x.brand}</p><strong>${money(x.price)}</strong></div><div class="quantity"><button onclick="changeQty(${x.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${x.id},1)">+</button></div></div>`).join(''):'<div class="empty-cart"><span>🛍️</span><h3>سلتك لسه فاضية</h3><p>اكتشفي براندات مصرية هتحبيها.</p></div>';document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#total').textContent=money(subtotal+35)}
function changeQty(id,n){const item=cart.find(x=>x.id===id);item.qty+=n;if(!item.qty)cart=cart.filter(x=>x.id!==id);renderCart()}
function toggleCart(){document.body.classList.toggle('cart-open')}
function checkout(){if(!cart.length)return;document.querySelector('#toast').textContent='تم تأكيد طلبك! هيوصلك خلال ساعتين.';document.querySelector('#toast').classList.add('show');cart=[];renderCart();toggleCart();setTimeout(()=>document.querySelector('#toast').classList.remove('show'),3000)}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');activeCategory=b.dataset.category;renderProducts()});renderProducts();renderBrands();renderCart();
