-- MVP relational schema for Qareeb's multi-brand ordering and routing workflow.
CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE, email TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE addresses (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), label TEXT, address TEXT NOT NULL, latitude DECIMAL(10,7), longitude DECIMAL(10,7), zone TEXT, is_default BOOLEAN DEFAULT FALSE);
CREATE TABLE brands (id INTEGER PRIMARY KEY, name TEXT NOT NULL, contact_name TEXT, phone TEXT, latitude DECIMAL(10,7), longitude DECIMAL(10,7), commission_rate DECIMAL(5,2) NOT NULL DEFAULT 15, outstanding_balance DECIMAL(12,2) DEFAULT 0, pickup_enabled BOOLEAN DEFAULT TRUE, active BOOLEAN DEFAULT TRUE);
CREATE TABLE categories (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE products (id INTEGER PRIMARY KEY, brand_id INTEGER NOT NULL REFERENCES brands(id), category_id INTEGER REFERENCES categories(id), name TEXT NOT NULL, description TEXT, price DECIMAL(12,2) NOT NULL, image_url TEXT, pickup_stock INTEGER DEFAULT 0, warehouse_stock INTEGER DEFAULT 0, source_mode TEXT CHECK(source_mode IN ('warehouse','brand','both')) DEFAULT 'both', prep_minutes INTEGER DEFAULT 15, active BOOLEAN DEFAULT TRUE);
CREATE TABLE riders (id INTEGER PRIMARY KEY, name TEXT NOT NULL, phone TEXT, zone TEXT, available BOOLEAN DEFAULT TRUE, latitude DECIMAL(10,7), longitude DECIMAL(10,7));
CREATE TABLE orders (id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(id), address_id INTEGER NOT NULL REFERENCES addresses(id), status TEXT CHECK(status IN ('confirmed','preparing','on_the_way','delivered','cancelled')) DEFAULT 'confirmed', ordered_at DATETIME DEFAULT CURRENT_TIMESTAMP, estimated_delivery_at DATETIME, delivered_at DATETIME, delivery_fee DECIMAL(12,2) NOT NULL, total DECIMAL(12,2) NOT NULL);
CREATE TABLE order_items (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), product_id INTEGER NOT NULL REFERENCES products(id), brand_id INTEGER NOT NULL REFERENCES brands(id), quantity INTEGER NOT NULL, unit_price DECIMAL(12,2) NOT NULL, fulfillment_source TEXT CHECK(fulfillment_source IN ('warehouse','brand')) NOT NULL);
CREATE TABLE deliveries (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), rider_id INTEGER REFERENCES riders(id), route_geojson TEXT, picked_up_at DATETIME, delivered_at DATETIME, status TEXT, estimated_minutes INTEGER);
CREATE TABLE invoices (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL UNIQUE REFERENCES orders(id), invoice_number TEXT NOT NULL UNIQUE, subtotal DECIMAL(12,2), delivery_fee DECIMAL(12,2), total DECIMAL(12,2), payment_status TEXT CHECK(payment_status IN ('pending','paid','failed')) DEFAULT 'pending', issued_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE payments (id INTEGER PRIMARY KEY, invoice_id INTEGER NOT NULL REFERENCES invoices(id), method TEXT CHECK(method IN ('cod','paymob','fawry','wallet')) NOT NULL, amount DECIMAL(12,2) NOT NULL, status TEXT CHECK(status IN ('pending','paid','failed')) DEFAULT 'pending', paid_at DATETIME, provider_reference TEXT);
CREATE TABLE settlements (id INTEGER PRIMARY KEY, brand_id INTEGER NOT NULL REFERENCES brands(id), period_start DATE NOT NULL, period_end DATE NOT NULL, gross_sales DECIMAL(12,2), commission DECIMAL(12,2), net_amount DECIMAL(12,2), status TEXT CHECK(status IN ('pending','paid')) DEFAULT 'pending', settled_at DATETIME);
